services:
  inference_service:
    build: ./Inference
    container_name: yolo_inference
    environment:
      STATS_PRINT: "true"
      RUNNING_PORT: "5000"
      STARTUP_STATUS: "idle"
      INPUT_SRC: "/dev/video0"
      MODEL_DIR: "/models"
      SOURCE_WIDTH: "1080"
      SOURCE_HEIGHT: "720"
      SOURCE_FPS: "30"
      LOOP_SLEEP_SECONDS: "0"
      MAX_UPLOAD_MB: "1024"
      # STARTUP_MODEL: "best.pt"

    privileged: true
    volumes:
      - ./Inference/models:/models:rw
      - /dev:/dev:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped
    # runtime: nvidia
